pipeline {
    agent any
    stages {
        stage('Gradle Build') {
            steps {
                sh 'sudo ./Backend/gradlew clean build -x test'
            }
        }

        stage('Build') {
            steps {
                sh 'docker build -t banana-back:latest .'
            }
        }

        stage('Deploy') {
            steps{
                sh 'docker rm -f back'
                sh 'docker run -d --name back -p 8099:8099 -v ~/back/resources:./Backend/src/main/resources -u root --network banana banana-back:latest'
            }
        }

       stage('Finish') {
            steps{
                sh 'docker images -qf dangling=true | xargs -I{} docker rmi {}'
            }
        }
    }
}