export const LOGIN_USER = "login_user"
export const SIGNUP_USER = "register_user"
export const CHECK_EMAIL = "check_email"
export const CHECK_EMAIL_CODE = "check_email_code"
export const CHECK_NICKNAME = "check_nickname"
export const SEND_CODE = "send_code"
export const LOGIN_CODE = "login_code"